# Generated by Django 6.1.1 on 2026-09-29 14:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail shop'), ('SUPERMARKET', 'Small supermarket'), ('WHOLESALE', 'Wholesaler'), ('PHARMACY', 'Pharmacy'), ('RESTAURANT', 'Restaurant'), ('SALON', 'Salon / barbershop'), ('SERVICE', 'Service business'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('owner_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(default='South Sudan', max_length=100)),
                ('currency', models.CharField(choices=[('SSP', 'SSP - South Sudanese Pound'), ('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('KES', 'KES - Kenyan Shilling'), ('UGX', 'UGX - Ugandan Shilling')], default='SSP', max_length=3)),
                ('tax_name', models.CharField(blank=True, max_length=30)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=10)),
                ('timezone', models.CharField(default='Africa/Juba', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='businesses.business')),
            ],
            options={
                'verbose_name_plural': 'branches',
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_branch_name'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('business',), name='unique_primary_branch_per_business')],
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='businesses__user_id_4ec985_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'user'), name='unique_membership')],
            },
        ),
    ]
